# Generated by Django 3.0.6 on 2020-06-10 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200609_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='codesnippet',
            name='original_snippet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.CodeSnippet'),
        ),
    ]
